### ISSUE TITLE
How can i make the popup open an URL only when clicked?

### ISSUE THREAD

**Issue by bognar-dev** [vardecab/win10toast-click#6]
When i try to put a Link into the `callback_on_click= webbrowser.open_new(f"https://www.flightradar24.com/{flight.id}")`
then it automatically opens it no matter if i clicked the Notification or not. Is it possible to make it only open the link when the notification is clicked?

**Comment by MrSuspicious0** [comment]
This is happening because you are passing a function in as a callback. When your interpreter reads that line it sees the function calll to `webbrowser.opennew()` amd executes it. You need to not call the function, so it would be `callback_on_click= webbrowser.open_new`. This uses the function as an object, but since you need to pass a parameter into it, you can use `partial` from the `functools` module in the standard library, as this will return a callback object for the function with the specified parameter.

The fixed code would look like this
you need `from functools import partial` at the top of your file, and then replace your snippet with `callback_on_click = partial(webbrowser.open_new, f"https://www.fightradar24.com/{flight.id}")`. This takes the open_new function as its first parameter (do NOT put brackets after it, as it will call the function) and the second parameter is the argument you want to be passed into the function, and it returns a callback.

Partial functions are hard to explain, but basically you need to learn the difference between a callback and a function. Regardless this code should fix your issue, hope this helped :)
